steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        _ADMIN_PASSWORD=$(gcloud secrets versions access latest --secret=PGBouncer_dbPassword)
        echo "ADMIN_PASSWORD=$_ADMIN_PASSWORD" >> env_file.env
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.0.0'
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export TF_VAR_name=pgbouncer
        export TF_VAR_database_host=10.11.64.3 
        export TF_VAR_port=6432
        export TF_VAR_project=slip-dev1
        export TF_VAR_zone=europe-west2-a
        export TF_VAR_users='[{"name":"admin","password":"'"$(cat env_file.env | grep ADMIN_PASSWORD | cut -d'=' -f2)"'"}]'
        terraform plan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export TF_VAR_name=pgbouncer
        export TF_VAR_database_host=10.11.64.3
        export TF_VAR_port=6432
        export TF_VAR_project=slip-dev1
        export TF_VAR_zone=europe-west2-a
        export TF_VAR_users='[{"name":"admin","password":"'"$(cat env_file.env | grep ADMIN_PASSWORD | cut -d'=' -f2)"'"}]'
        terraform apply --auto-approve
options:
  logging: CLOUD_LOGGING_ONLY